### ISSUE TITLE
Tone.text

### ISSUE THREAD

**Issue by lxa520** [rogerclarkmelbourne/radioddity_gd-77_cps#44] opened 2018-03-26 06:25 UTC
first line;
none delete，add by code in multi-language

**Comment by rogerclarkmelbourne** [comment] 2018-03-26 06:32
OK.
There was another bug for None on TxTone and Admit criteria but I fixed this.

**Comment by rogerclarkmelbourne** [comment] 2018-03-26 06:38
Are any of these bugs fixed in CPS 3.1.0 ?   As I have tried to decompile that, but it takes too much time, so I'll just modify 3.0.6 to make CPS 3.1.1 when its released.

**Comment by lxa520** [comment] 2018-03-26 06:45
3.10 is fixed this bug

**Comment by rogerclarkmelbourne** [comment] 2018-03-26 06:46
Ah,

I see.
This change is in CPS 3.1.0

Tone setting can not be None any more.

I will need to test if this is a problem for existing codeplugs

**Comment by rogerclarkmelbourne** [comment] 2018-03-26 06:48
OK

**Comment by rogerclarkmelbourne** [comment] 2018-04-02 09:56
I have not changed this in my CPS but I did fix the bug caused by setting Admin Critera not enough options.

**Comment by lxa520** [comment] 2018-04-03 00:39
You mentioned the CTCSS BUG many times, 
How much do you fix the version of this BUG

**Comment by lxa520** [comment] 2018-04-03 00:44
only the "tx tone" is not "none", the "admit criteria" have "ctcss/dcs" option. i dont konw the bug which you said, you can provide the version which you fixed it.

**Comment by rogerclarkmelbourne** [comment] 2018-04-03 01:26
I will raise separate issue and explain

**Comment by rogerclarkmelbourne** [comment] 2018-04-03 01:33
I made new issue for you

https://github.com/rogerclarkmelbourne/radioddity_gd-77_cps2.0.5/issues/48

You can see my fix. Its easy ;-)

**Comment by rogerclarkmelbourne** [comment] 2018-11-11 21:38
Closed due to no response in more than 6 months

**Closed by rogerclarkmelbourne** 2018-11-11 21:38 UTC
